config/routes.rb
NewYorkTimesEvents::Application.routes.draw do
  resources :maps

end

app/models/event.rb
class Event

  attr_accessor :event_id, :event_schedule_id, :last_modified, :event_name, :event_detail_url, :web_description, :city, :state, :film_rating,
    :critic_name, :category, :times_pick, :free, :kid_friendly, :last_chance, :festival, :long_running_show, :previews_and_openings,
    :recurring_start_date, :recur_days, :venue_name, :geocode_latitude, :geocode_longitude, :borough, :neighborhood, :cross_street, :postal_code,
    :telephone, :venue_website, :subcategory, :theater_overview_url, :theater_ticket_url,
    :date_time_description, :street_address, :theater_review_url, :venue_detail_url, :recurring_end_date

  def initialize(attrs = {})
    attrs.each do |k, v|
      send "#{k}=", v
    end
  end

end

app/models/get_events.rb
class GetEvents

  attr_accessor :categories, :latitude, :longitude

  def initialize(categories, latitude, longitude)
    @categories = categories
    @latitude = latitude
    @longitude = longitude
  end

  def get_events
    events = Array.new
    response = HTTParty.get(url,
      :query => {:oauth_token => "abc"})
    json = JSON.parse(response.body)
    json["results"].each do |event|
      events.push Event.new(event)
    end
  end

  private
    def url
      "http://api.nytimes.com/svc/events/#{version}/listings#{response_format}?#{radius}&filters=category:(#{category_list})&api-key=#{api_key}"
    end

    def radius
      "11=#{latitude},#{longitude}"
    end

    def version
      "v2"
    end

    def api_key
      "1b6ec24de1512db2fae47f5165ce39ea:6:69563513"
    end

    def response_format
      ".json"
    end

    def category_list
      categories.join('+')
    end

end

app/models/map.rb
class Map
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index

  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render action: 'show', status: :created, location: @map }
      else
        format.html { render action: 'new' }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params[:map]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewYorkTimesEvents</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/maps/_form.html.erb
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing map</h1>

<%= render 'form' %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 100px; padding: 10px }
      #map-canvas { height: 500px; width: 1000px; margin: 100px; padding: 10px }
    </style>
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBL0opyQmQ0D_RJQcHVPkIVmQXYEGnOj7k">
    </script>
    <script type="text/javascript">
      function initialize() {
        var mapOptions = {
          center: new google.maps.LatLng(40.7127, -74.0059),
          zoom: 14
        };
        var map = new google.maps.Map(document.getElementById("map-canvas"),
            mapOptions);
        setMarkers(map, events);
      }
      var events = [
        ['Event 1', 40.7127, -74.0059],
        ['Event 2', 40.7117, -74.0125],
        ['Event 2', 40.6892, -74.0444]
      ]

      function setMarkers(map, locations) {
        for (var i = 0; i < locations.length; i++) {
          var myEvent = locations[i];
          var myLatLng = new google.maps.LatLng(myEvent[1], myEvent[2]);
          var marker = new google.maps.Marker({
              position: myLatLng,
              map: map,
              title: myEvent[0]
          });
        }
      }
      // google.maps.event.addListener(map, 'bounds_changed', function() {map.setZoom(8)}
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
  </head>
  <body>
  <h1>New York Times: Events</h1>
  <hr>
    <div id="map-canvas"/>
  </body>
</html>

app/views/maps/new.html.erb
<h1>New map</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>